# Generated by Django 5.2.1 on 2025-05-20 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('preview_text', models.CharField(blank=True, max_length=250, null=True)),
                ('artical_url', models.URLField(blank=True, null=True)),
                ('html_content', models.TextField(help_text='Main HTML body of the email. Variable like {{first_name}},{{unsubscriber_url}} can be used.')),
                ('plain_text_content', models.TextField(help_text='Plain text version . Variables like {{first_name}} , {{unsubscribe_url}} can be used.')),
                ('published_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('is_sent', models.BooleanField(db_index=True, default=False)),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
